### Swagger Details
### http://localhost:8080/swagger-ui

### Demo - Decision Service
### 1. Traffic Violation - Specification/Metadata XML
GET http://localhost:8080/TrafficViolation

### 2. Traffic Violation - Decision Service[DriverSuspention]
POST http://localhost:8080/TrafficViolation/DriverSuspention
Content-Type: application/json
Accept: application/json

{
    "Driver":{
        "Name": "John Doe",
        "Age": 19,
        "State": "California",
        "City": "Los Angeles",
        "Points": 17
    },
    "Violation": {
        "Code": "001",
        "Date": "2020-11-03",
        "Type": "Speed",
        "SpeedLimit": 100,
        "ActualSpeed": 200
    }
}

### 3. Traffic Violation
POST http://localhost:8080/TrafficViolation
Content-Type: application/json
Accept: application/json

{
    "Driver":{
        "Name": "John Doe",
        "Age": 19,
        "State": "California",
        "City": "Los Angeles",
        "Points": 14
    },
    "Violation": {
        "Code": "001",
        "Date": "2020-11-03",
        "Type": "Speed",
        "SpeedLimit": 100,
        "ActualSpeed": 200
    }
}

### Demo - Recurssion
### 4. FibonaciListGenerator from 1 to 45 i.e. 9 sequences
POST http://localhost:8080/FibonaciListGenerator
Content-Type: application/json
Accept: application/json



### Demo - Complex Business Usecase
### x. Loan Calculator
POST http://localhost:8080/LoanCalculator
Content-Type: application/json
Accept: application/json

{
    "LoanDetails":{
       "Amount":18700,
       "Rate":12,
       "Term":12
    }
}

### x. Lease Calculator Rentfactor Based
POST http://localhost:8080/LeaseCalculator
Content-Type: application/json
Accept: application/json

{
    "LeaseDetails":{
       "GrossCapitalizedCost":18700,
       "CapitalizedCostReduction":0,
       "ResidualPercentage":0,
       "Rate":12,
       "Term":12
    }
}

### x. Lease Calculator Interest Bearning
POST http://localhost:8080/LeaseCalculatorIBL
Content-Type: application/json
Accept: application/json

{
    "LeaseDetails":{
       "GrossCapitalizedCost":18700,
       "CapitalizedCostReduction":0,
       "ResidualPercentage":0,
       "Rate":12,
       "Term":12
    }
}
