### Swagger Details
### http://localhost:8080/swagger-ui

### Demo - Decision Service
### 1. Traffic Violation - Specification/Metadata XML
GET http://localhost:8080/TrafficViolation

### 2. Traffic Violation - Decision Service[DriverSuspention]
POST http://localhost:8080/TrafficViolation/DriverSuspention
Content-Type: application/json
Accept: application/json

{
    "Driver":{
        "Name": "John Doe",
        "Age": 19,
        "State": "California",
        "City": "Los Angeles",
        "Points": 17
    },
    "Violation": {
        "Code": "001",
        "Date": "2020-11-03",
        "Type": "Speed",
        "SpeedLimit": 100,
        "ActualSpeed": 200
    }
}

### 3. Traffic Violation
POST http://localhost:8080/TrafficViolation
Content-Type: application/json
Accept: application/json

{
    "Driver":{
        "Name": "John Doe",
        "Age": 19,
        "State": "California",
        "City": "Los Angeles",
        "Points": 14
    },
    "Violation": {
        "Code": "001",
        "Date": "2020-11-03",
        "Type": "Speed",
        "SpeedLimit": 100,
        "ActualSpeed": 200
    }
}

### Demo - Recurssion
### 4. FibonaciListGenerator from 1 to 45 i.e. 9 sequences
POST http://localhost:8080/FibonaciListGenerator
Content-Type: application/json
Accept: application/json

### Demo - Filtering
### 5. List All Manager https://apex.oracle.com/pls/apex/oraclejet/emp/
POST http://localhost:8080/filter
Content-Type: application/json
Accept: application/json

{
	"Employees": [
        {
			"empno": 7839,
			"ename": "KING",
			"job": "PRESIDENT",
			"mgr": null,
			"hiredate": "1981-11-17T00:00:00Z",
			"sal": 5000,
			"comm": null,
			"deptno": 10
		},
		{
			"empno": 7698,
			"ename": "BLAKE",
			"job": "MANAGER",
			"mgr": 7839,
			"hiredate": "1981-05-01T00:00:00Z",
			"sal": 2850,
			"comm": null,
			"deptno": 30
		},
		{
			"empno": 7782,
			"ename": "CLARK",
			"job": "MANAGER",
			"mgr": 7839,
			"hiredate": "1981-06-09T00:00:00Z",
			"sal": 2450,
			"comm": null,
			"deptno": 10
		},
		{
			"empno": 7566,
			"ename": "JONES",
			"job": "MANAGER",
			"mgr": 7839,
			"hiredate": "1981-04-02T00:00:00Z",
			"sal": 2975,
			"comm": null,
			"deptno": 20
		},
		{
			"empno": 7788,
			"ename": "SCOTT",
			"job": "ANALYST",
			"mgr": 7566,
			"hiredate": "1982-12-09T00:00:00Z",
			"sal": 3000,
			"comm": null,
			"deptno": 20
		},
		{
			"empno": 7902,
			"ename": "FORD",
			"job": "ANALYST",
			"mgr": 7566,
			"hiredate": "1981-12-03T00:00:00Z",
			"sal": 3000,
			"comm": null,
			"deptno": 20
		},
		{
			"empno": 7369,
			"ename": "SMITH",
			"job": "CLERK",
			"mgr": 7902,
			"hiredate": "1980-12-17T00:00:00Z",
			"sal": 800,
			"comm": null,
			"deptno": 20
		},
		{
			"empno": 7499,
			"ename": "ALLEN",
			"job": "SALESMAN",
			"mgr": 7698,
			"hiredate": "1981-02-20T00:00:00Z",
			"sal": 1600,
			"comm": 300,
			"deptno": 30
		},
		{
			"empno": 7521,
			"ename": "WARD",
			"job": "SALESMAN",
			"mgr": 7698,
			"hiredate": "1981-02-22T00:00:00Z",
			"sal": 1250,
			"comm": 500,
			"deptno": 30
		},
		{
			"empno": 7654,
			"ename": "MARTIN",
			"job": "SALESMAN",
			"mgr": 7698,
			"hiredate": "1981-09-28T00:00:00Z",
			"sal": 1250,
			"comm": 1400,
			"deptno": 30
		},
		{
			"empno": 7844,
			"ename": "TURNER",
			"job": "SALESMAN",
			"mgr": 7698,
			"hiredate": "1981-09-08T00:00:00Z",
			"sal": 1500,
			"comm": 0,
			"deptno": 30
		},
		{
			"empno": 7876,
			"ename": "ADAMS",
			"job": "CLERK",
			"mgr": 7788,
			"hiredate": "1983-01-12T00:00:00Z",
			"sal": 1100,
			"comm": null,
			"deptno": 20
		},
		{
			"empno": 7900,
			"ename": "JAMES",
			"job": "CLERK",
			"mgr": 7698,
			"hiredate": "1981-12-03T00:00:00Z",
			"sal": 950,
			"comm": null,
			"deptno": 30
		},
		{
			"empno": 7934,
			"ename": "MILLER",
			"job": "CLERK",
			"mgr": 7782,
			"hiredate": "1982-01-23T00:00:00Z",
			"sal": 1300,
			"comm": null,
			"deptno": 10
		}
	]
}


### Demo - Complex Business Usecase
### x. Loan Calculator
POST http://localhost:8080/LoanCalculator
Content-Type: application/json
Accept: application/json

{
    "LoanDetails":{
       "Amount":18700,
       "Rate":12,
       "Term":12
    }
}

### x. Lease Calculator Rentfactor Based
POST http://localhost:8080/LeaseCalculator
Content-Type: application/json
Accept: application/json

{
    "LeaseDetails":{
       "GrossCapitalizedCost":18700,
       "CapitalizedCostReduction":0,
       "ResidualPercentage":0,
       "Rate":12,
       "Term":12
    }
}

### x. Lease Calculator Interest Bearning
POST http://localhost:8080/LeaseCalculatorIBL
Content-Type: application/json
Accept: application/json

{
    "LeaseDetails":{
       "GrossCapitalizedCost":18700,
       "CapitalizedCostReduction":0,
       "ResidualPercentage":0,
       "Rate":12,
       "Term":12
    }
}
